Models/Medicamento.cs
using System.ComponentModel.DataAnnotations;

namespace ProyectoProgramadoLenguajes2024.Models
{
    public class Medicamento
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Nombre { get; set; }



    }
}

Areas/Medicina/Controllers/MedicamentoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoProgramadoLenguajes2024.Data.Repository.Interfaces;
using ProyectoProgramadoLenguajes2024.Models;
using ProyectoProgramadoLenguajes2024.Models.ViewModels;
using ProyectoProgramadoLenguajes2024.Utilities;

namespace ProyectoProgramadoLenguajes2024.Areas.Medicina.Controllers
{
    [Area("Medicina")]
    [Authorize(Roles = Roles.Medico)]
    public class MedicamentoController: Controller
    {
        #region Properties_Constructor
        private IUnitOfWork _unitOfWork;

        public MedicamentoController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        #endregion


        #region HTTP_GET

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            MedicamentoVM myMedicamento = new()
            {
                Medicamento = new Medicamento(),
                MedicamentoList = _unitOfWork.Medicamento.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Nombre,
                    Value = i.Id.ToString()
                }).ToList()
            };

            if (id == null || id == 0)
            {
                return View(myMedicamento);
            }

            myMedicamento.Medicamento = _unitOfWork.Medicamento.Get(x => x.Id == id);
            if (myMedicamento.Medicamento == null)
            {
                return NotFound();
            }

            return View(myMedicamento);
        }
        #endregion
        #region HTTP_POST

        [HttpPost]
        public IActionResult Upsert(MedicamentoVM _medicamentoVM)
        {
            if (ModelState.IsValid)
            {

                if (_medicamentoVM.Medicamento.Id == 0)
                    _unitOfWork.Medicamento.Add(_medicamentoVM.Medicamento);
                else
                    _unitOfWork.Medicamento.Update(_medicamentoVM.Medicamento);

                _unitOfWork.Save();
                TempData["success"] = "Medicamento agregado exitosamente";

            }

            return RedirectToAction("Index");
        }
        #endregion

        #region API
        public IActionResult GetAll()
        {
            var medicamentoList = _unitOfWork.Medicamento.GetAll().Select(c => new {
                c.Id,
                c.Nombre

            });
            return Json(new { data = medicamentoList });

        }


        public IActionResult Delete(int? id)
        {
            var medicamentoToDelete = _unitOfWork.Medicamento.Get(x => x.Id == id);

            if (medicamentoToDelete == null)
            {
                return Json(new { success = false, message = "Error al borrar el medicamento" });
            }

            _unitOfWork.Medicamento.Remove(medicamentoToDelete);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Medicamento borrado exitosamente" });
        }
        #endregion
    }
}

Areas/Usuario/Controllers/MedicamentosController.cs
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProyectoProgramadoLenguajes2024.Data.Repository.Interfaces;

namespace ProyectoProgramadoLenguajes2024.Areas.Usuario.Controllers
{
    [Area("Usuario")]
    [EnableCors("AllowAnyOrigin")]
    public class MedicamentosController : Controller
    {

        [HttpGet]
        [EnableCors("AllowAnyOrigin")]
        public IActionResult GetMedicamentos(int id)
        {
            var unitOfWork = HttpContext.RequestServices.GetService<IUnitOfWork>() as IUnitOfWork;

            var medicamentos = unitOfWork.MedicamentosPacientes.GetAll(includeProperties: "Medicamento,MedicoTratante")
                                   .Where(x => x.CedulaPaciente == id);
            return Json(new { data = medicamentos });
        }
    }
}

Areas/Medicina/Views/Medicamento/Index.cshtml
<partial name="_Notifications" />

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Lista de Medicamentos
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-area="Medicina" asp-controller="Medicamento" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Agregar Medicamento
            </a>
        </div>
    </div>

    <table id="tblData" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Acciones</th>
            </tr>
        </thead>
    </table>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/medicamento.js"></script>

Areas/Medicina/Views/Medicamento/Upsert.cshtml
@using ProyectoProgramadoLenguajes2024.Models.ViewModels
@model MedicamentoVM
<partial name="_Notifications" />

<form method="post">

    <input hidden asp-for="Medicamento.Id" />

    <div class="mb-3">
        <div class="row pb-2">
            <h2 class="text-primary"> @(Model.Medicamento.Id == 0 ? "Crear" : "Actualizar") Medicamento</h2>
        </div>
    </div>

      

        <div class="mb-3">
                <label asp-for="Medicamento.Nombre" class="p-0"></label>
                <input asp-for="Medicamento.Nombre" type="text" class="form-control" />
                <span asp-validation-for="Medicamento.Nombre" class="text-danger"></span>
        </div>
           


        <button type="submit" class="btn btn-primary" style="width:150px">Guardar</button>
            <a asp-controller="Medicamento" asp-action="Index" style="width:200px" class="btn btn-secondary">Regresar a la lista</a>
  


</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}