Models/Especialidad.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace ProyectoProgramadoLenguajes2024.Models
{
    
    public class Especialidad
    {

        [Key]
        public int Id { get; set; }

        [Required]
        public string Nombre { get; set; }
    }
}

Areas/Admin/Controllers/EspecialidadController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoProgramadoLenguajes2024.Data.Repository.Interfaces;
using ProyectoProgramadoLenguajes2024.Models;
using ProyectoProgramadoLenguajes2024.Models.ViewModels;
using ProyectoProgramadoLenguajes2024.Utilities;

namespace ProyectoProgramadoLenguajes2024.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class EspecialidadController : Controller
    {
        #region Properties_Constructor
        private IUnitOfWork _unitOfWork;

        public EspecialidadController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        
        public IActionResult Index()
        {
            return View();
        }
        #endregion


        #region HTTP_GET

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            EspecialidadVM myEspecialidad = new()
            {
                Especialidad = new Especialidad(),
                EspecialidadList = _unitOfWork.Especialidades.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Nombre,
                    Value = i.Id.ToString()
                }).ToList()
            };

            if (id == null || id == 0)
            {
                return View(myEspecialidad);
            }

            myEspecialidad.Especialidad = _unitOfWork.Especialidades.Get(x => x.Id == id);
            if (myEspecialidad.Especialidad == null)
            {
                return NotFound();
            }

            return View(myEspecialidad);
        }


        #endregion

        #region HTTP_POST

        [HttpPost]
        public IActionResult Upsert(EspecialidadVM _especialidadVM)
        {
            if (ModelState.IsValid)
            {

                if (_especialidadVM.Especialidad.Id == 0)
                    _unitOfWork.Especialidades.Add(_especialidadVM.Especialidad);
                else
                    _unitOfWork.Especialidades.Update(_especialidadVM.Especialidad);

                _unitOfWork.Save();
                TempData["success"] = "Especialidad agregada exitosamente";
                
            }
          
            return RedirectToAction("Index");

        }



        #endregion

        #region API
        public IActionResult GetAll()
        {
            var especialidadList = _unitOfWork.Especialidades.GetAll().Select(c => new {
                c.Id,
                c.Nombre
            });
            return Json(new { data = especialidadList });

        }


        public IActionResult Delete(int? id)
        {
            var especialidadToDelete = _unitOfWork.Especialidades.Get(x => x.Id == id);

            if (especialidadToDelete == null)
            {
                return Json(new { success = false, message = "Error al borrar la especialidad" });
            }

            _unitOfWork.Especialidades.Remove(especialidadToDelete);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Especialidad borrada exitosamente" });
        }
        #endregion

    }
}

Areas/Admin/Views/Especialidad/Index.cshtml
@{
    ViewData["Title"] = "Lista de Especialidades";
}


<partial name="_Notifications" />

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Lista de especialidades
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-area="Admin" asp-controller="Especialidad" asp-action="Upsert" class="btn btn-primary"> <i class="bi bi-plus-circle"></i> Crear especialidad
            </a>
        </div>
    </div>

    <table id="tblData" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Acciones</th>
            </tr>
        </thead>
    </table>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/especialidad.js"></script>

Areas/Admin/Views/Especialidad/Upsert.cshtml
@using ProyectoProgramadoLenguajes2024.Models.ViewModels
@model EspecialidadVM
<partial name="_Notifications" />

<form method="post">

    <input hidden asp-for="Especialidad.Id" />

  
        <div class="row pb-2">
            <h2 class="text-primary"> @(Model.Especialidad.Id == 0 ? "Crear" : "Actualizar") Especialidad</h2>
        </div>
  

        <div class="mb-3">
            <label asp-for="Especialidad.Nombre" class="p-0"></label>
            <input asp-for="Especialidad.Nombre" type="text" class="form-control" />
            <span asp-validation-for="Especialidad.Nombre" class="text-danger"></span>
        </div>


        <button type="submit" class="btn btn-primary" style="width:150px">Guardar</button>
        <a asp-controller="Especialidad" asp-action="Index" style="width:200px" class="btn btn-secondary">Regresar a la lista</a>
   


</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}