Models/Medicamento.cs
using System.ComponentModel.DataAnnotations;

namespace ProyectoProgramadoLenguajes2024.Models
{
    public class Medicamento
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Nombre { get; set; }



    }
}

Models/Paciente.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProyectoProgramadoLenguajes2024.Models
{
    public class Paciente
    {
        [Key]
        public int Cedula { get; set; }
        [Required]
        public string NombreCompleto { get; set; }
        [Required]
        public string CorreoElectronico { get; set; }
        

    }
}

Models/Padecimiento.cs
using System.ComponentModel.DataAnnotations;

namespace ProyectoProgramadoLenguajes2024.Models
{
    public class Padecimiento
    {

        [Key]
        public int Id { get; set; }

        [Required]
        public string Nombre { get; set; }

        [Required]
        public string Descripcion { get; set; }
    }
}

Models/Tratamiento.cs
using System.ComponentModel.DataAnnotations;

namespace ProyectoProgramadoLenguajes2024.Models
{
    public class Tratamiento
    {

        [Key]
        public int Id { get; set; }

        [Required]
        public string Nombre { get; set; }

        [Required]
        public string Descripcion { get; set; }


    }
}

Areas/Admin/Controllers/PacienteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoProgramadoLenguajes2024.Data.Repository.Interfaces;
using ProyectoProgramadoLenguajes2024.Models;
using ProyectoProgramadoLenguajes2024.Models.ViewModels;
using ProyectoProgramadoLenguajes2024.Utilities;

namespace ProyectoProgramadoLenguajes2024.Areas.Admin.Controllers
{
    [Area("Admin")]

    [Authorize(Roles = Roles.Admin)]

    public class PacienteController : Controller
    {
        #region Properties_Constructor
        private IUnitOfWork _unitOfWork;

        private readonly UserManager<IdentityUser> _userManager;



        public PacienteController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;

        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult GetAll()
        {
            var pacientesList = _unitOfWork.Pacientes.GetAll().Select(c => new
            {
                c.Cedula,
                c.NombreCompleto,
                c.CorreoElectronico
            });
            return Json(new { data = pacientesList });
        }
        #endregion

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            PacienteVM myPaciente = new()
            {
                Paciente = new Paciente(),
                PacientesList = _unitOfWork.Pacientes.GetAll().Select(i => new SelectListItem
                {
                    Text = i.NombreCompleto,
                    Value = i.Cedula.ToString()
                }).ToList()
            };

            if (id == null || id == 0)
            {
                return View(myPaciente);
            }

            myPaciente.Paciente = _unitOfWork.Pacientes.Get(x => x.Cedula == id);
            if (myPaciente.Paciente == null)
            {
                return NotFound();
            }

            return View(myPaciente);
        }

        [HttpPost]
        public IActionResult Upsert(PacienteVM _pacienteVM)
        {
            if (ModelState.IsValid)
            {

                if (_pacienteVM.Paciente.Cedula == 0)
                {
                    _unitOfWork.Pacientes.Add(_pacienteVM.Paciente);
                }
                else
                {
                    _unitOfWork.Pacientes.Update(_pacienteVM.Paciente);
                }

                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            return View(_pacienteVM);
        }




        



        public IActionResult Delete(int? id)
        {
            var pacienteToDelete = _unitOfWork.Pacientes.Get(x => x.Cedula == id);



            if (pacienteToDelete != null)
            {
                var padecimientosPaciente = _unitOfWork.PadecimientosPacientes.GetAll().Where(x => x.CedulaPaciente == id).ToList();
                var tratamientosPaciente = _unitOfWork.TratamientosPacientes.GetAll().Where(x => x.CedulaPaciente == id).ToList();
                var medicamentosPaciente = _unitOfWork.MedicamentosPacientes.GetAll().Where(x => x.CedulaPaciente == id).ToList();
                var examenesPaciente = _unitOfWork.ExamenesPacientes.GetAll().Where(x => x.CedulaPaciente == id).ToList();
                var notasMedicas = _unitOfWork.NotasMedicas.GetAll().Where(x => x.CedulaPaciente == id).ToList();

                foreach (var padecimientoPaciente in padecimientosPaciente)
                {
                    _unitOfWork.PadecimientosPacientes.Remove(padecimientoPaciente);
                }

                foreach (var tratamientoPaciente in tratamientosPaciente)
                {
                    _unitOfWork.TratamientosPacientes.Remove(tratamientoPaciente);
                }

                foreach (var medicamentoPaciente in medicamentosPaciente)
                {
                    _unitOfWork.MedicamentosPacientes.Remove(medicamentoPaciente);
                }

                foreach (var examenPaciente in examenesPaciente)
                {
                    _unitOfWork.ExamenesPacientes.Remove(examenPaciente);
                }

                foreach (var notaMedica in notasMedicas)
                {
                    _unitOfWork.NotasMedicas.Remove(notaMedica);
                }

                _unitOfWork.Pacientes.Remove(pacienteToDelete);
                _unitOfWork.Save();
                return Json(new { success = true, message = "Paciente borrado exitosamente" });
            }


            return Json(new { success = false, message = "Error al borrar el paciente" });

        }
    }
}

Areas/Medicina/Controllers/MedicamentoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoProgramadoLenguajes2024.Data.Repository.Interfaces;
using ProyectoProgramadoLenguajes2024.Models;
using ProyectoProgramadoLenguajes2024.Models.ViewModels;
using ProyectoProgramadoLenguajes2024.Utilities;

namespace ProyectoProgramadoLenguajes2024.Areas.Medicina.Controllers
{
    [Area("Medicina")]
    [Authorize(Roles = Roles.Medico)]
    public class MedicamentoController: Controller
    {
        #region Properties_Constructor
        private IUnitOfWork _unitOfWork;

        public MedicamentoController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        #endregion


        #region HTTP_GET

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            MedicamentoVM myMedicamento = new()
            {
                Medicamento = new Medicamento(),
                MedicamentoList = _unitOfWork.Medicamento.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Nombre,
                    Value = i.Id.ToString()
                }).ToList()
            };

            if (id == null || id == 0)
            {
                return View(myMedicamento);
            }

            myMedicamento.Medicamento = _unitOfWork.Medicamento.Get(x => x.Id == id);
            if (myMedicamento.Medicamento == null)
            {
                return NotFound();
            }

            return View(myMedicamento);
        }
        #endregion
        #region HTTP_POST

        [HttpPost]
        public IActionResult Upsert(MedicamentoVM _medicamentoVM)
        {
            if (ModelState.IsValid)
            {

                if (_medicamentoVM.Medicamento.Id == 0)
                    _unitOfWork.Medicamento.Add(_medicamentoVM.Medicamento);
                else
                    _unitOfWork.Medicamento.Update(_medicamentoVM.Medicamento);

                _unitOfWork.Save();
                TempData["success"] = "Medicamento agregado exitosamente";

            }

            return RedirectToAction("Index");
        }
        #endregion

        #region API
        public IActionResult GetAll()
        {
            var medicamentoList = _unitOfWork.Medicamento.GetAll().Select(c => new {
                c.Id,
                c.Nombre

            });
            return Json(new { data = medicamentoList });

        }


        public IActionResult Delete(int? id)
        {
            var medicamentoToDelete = _unitOfWork.Medicamento.Get(x => x.Id == id);

            if (medicamentoToDelete == null)
            {
                return Json(new { success = false, message = "Error al borrar el medicamento" });
            }

            _unitOfWork.Medicamento.Remove(medicamentoToDelete);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Medicamento borrado exitosamente" });
        }
        #endregion
    }
}

Areas/Medicina/Controllers/PadecimientoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoProgramadoLenguajes2024.Data.Repository.Interfaces;
using ProyectoProgramadoLenguajes2024.Models.ViewModels;
using ProyectoProgramadoLenguajes2024.Models;
using Microsoft.AspNetCore.Authorization;
using ProyectoProgramadoLenguajes2024.Utilities;

namespace ProyectoProgramadoLenguajes2024.Areas.Medicina.Controllers
{
    [Area("Medicina")]
    [Authorize(Roles = Roles.Medico)]
    public class PadecimientoController : Controller
    {
        #region Properties_Constructor
        private IUnitOfWork _unitOfWork;

        public PadecimientoController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }



        public IActionResult Index()
        {
            return View();
        }
        #endregion


        #region HTTP_GET

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            PadecimientoVM myPadecimiento = new()
            {
                Padecimiento = new Padecimiento(),
                PadecimientoList = _unitOfWork.Padecimiento.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Nombre,
                    Value = i.Id.ToString()
                }).ToList()
            };

            if (id == null || id == 0)
            {
                return View(myPadecimiento);
            }

            myPadecimiento.Padecimiento = _unitOfWork.Padecimiento.Get(x => x.Id == id);
            if (myPadecimiento.Padecimiento == null)
            {
                return NotFound();
            }

            return View(myPadecimiento);
        }


        #endregion

        #region HTTP_POST

        [HttpPost]
        public IActionResult Upsert(PadecimientoVM _padecimientoVM)
        {
            if (ModelState.IsValid)
            {

                if (_padecimientoVM.Padecimiento.Id == 0)
                    _unitOfWork.Padecimiento.Add(_padecimientoVM.Padecimiento);
                else
                    _unitOfWork.Padecimiento.Update(_padecimientoVM.Padecimiento);

                _unitOfWork.Save();
                TempData["success"] = "Padecimiento agregado exitosamente";

            }

            return RedirectToAction("Index");

        }



        #endregion

        #region API
        public IActionResult GetAll()
        {
            var padecimientoList = _unitOfWork.Padecimiento.GetAll().Select(c => new {
                c.Id,
                c.Nombre,
                c.Descripcion

            });
            return Json(new { data = padecimientoList });

        }


        public IActionResult Delete(int? id)
        {
            var padecimientoToDelete = _unitOfWork.Padecimiento.Get(x => x.Id == id);

            if (padecimientoToDelete == null)
            {
                return Json(new { success = false, message = "Error al borrar el padecimiento" });
            }

            _unitOfWork.Padecimiento.Remove(padecimientoToDelete);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Padecimiento borrada exitosamente" });
        }
        #endregion

    }
}

Areas/Medicina/Controllers/TratamientoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoProgramadoLenguajes2024.Data.Repository.Interfaces;
using ProyectoProgramadoLenguajes2024.Models.ViewModels;
using ProyectoProgramadoLenguajes2024.Models;
using ProyectoProgramadoLenguajes2024.Utilities;

namespace ProyectoProgramadoLenguajes2024.Areas.Medicina.Controllers
{
    [Area("Medicina")]
    [Authorize(Roles = Roles.Medico)]
    public class TratamientoController : Controller
    {
        #region Properties_Constructor
        private IUnitOfWork _unitOfWork;

        public TratamientoController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        #endregion


        #region HTTP_GET

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            TratamientoVM myTratamiento = new()
            {
                Tratamiento = new Tratamiento(),
                TratamientoList = _unitOfWork.Tratamiento.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Nombre,
                    Value = i.Id.ToString()
                }).ToList()
            };

            if (id == null || id == 0)
            {
                return View(myTratamiento);
            }

            myTratamiento.Tratamiento = _unitOfWork.Tratamiento.Get(x => x.Id == id);
            if (myTratamiento.Tratamiento == null)
            {
                return NotFound();
            }

            return View(myTratamiento);
        }

        #endregion

        #region HTTP_POST

        [HttpPost]
        public IActionResult Upsert(TratamientoVM _tratamientoVM)
        {
            if (ModelState.IsValid)
            {

                if (_tratamientoVM.Tratamiento.Id == 0)
                    _unitOfWork.Tratamiento.Add(_tratamientoVM.Tratamiento);
                else
                    _unitOfWork.Tratamiento.Update(_tratamientoVM.Tratamiento);

                _unitOfWork.Save();
                TempData["success"] = "Tratamiento agregado exitosamente";

            }

            return RedirectToAction("Index");

        }
        #endregion

        #region API
        public IActionResult GetAll()
        {
            var tratamientoList = _unitOfWork.Tratamiento.GetAll().Select(c => new {
                c.Id,
                c.Nombre,
                c.Descripcion

            });
            return Json(new { data = tratamientoList });

        }


        public IActionResult Delete(int? id)
        {
            var tratamientoToDelete = _unitOfWork.Tratamiento.Get(x => x.Id == id);

            if (tratamientoToDelete == null)
            {
                return Json(new { success = false, message = "Error al borrar el tratamiento" });
            }

            _unitOfWork.Tratamiento.Remove(tratamientoToDelete);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Tratamiento borrado exitosamente" });
        }
        #endregion
    }
}

Areas/Usuario/Controllers/MedicamentosController.cs
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProyectoProgramadoLenguajes2024.Data.Repository.Interfaces;

namespace ProyectoProgramadoLenguajes2024.Areas.Usuario.Controllers
{
    [Area("Usuario")]
    [EnableCors("AllowAnyOrigin")]
    public class MedicamentosController : Controller
    {

        [HttpGet]
        [EnableCors("AllowAnyOrigin")]
        public IActionResult GetMedicamentos(int id)
        {
            var unitOfWork = HttpContext.RequestServices.GetService<IUnitOfWork>() as IUnitOfWork;

            var medicamentos = unitOfWork.MedicamentosPacientes.GetAll(includeProperties: "Medicamento,MedicoTratante")
                                   .Where(x => x.CedulaPaciente == id);
            return Json(new { data = medicamentos });
        }
    }
}

Areas/Medicina/Views/Paciente/AgregarExamenesMedicos.cshtml
@using ProyectoProgramadoLenguajes2024.Models.ViewModels
@model ExpedienteVM

<div class="container">
    <div class="card-body">
        <div class="row pt-4">
            <div class="col-6">
                <h2 class="text-primary">
                    Agregar Examen Médico
                </h2>
            </div>
        <form asp-action="AgregarExamenesMedicos" enctype="multipart/form-data" method="post">

            <div class="mb-3">
                <label asp-for="ExamenVM.Examen.Descripcion" class="form-label">Descripción</label>
                <input asp-for="ExamenVM.Examen.Descripcion" class="form-control" />
            </div>

            <div class="mb-3">
                <label asp-for="ExamenVM.Examen.ArchivoURL" class="form-label">PDF o Imagen</label>
                <input id="uploadBox" name="file" type="file" class="form-control" />
                <span asp-validation-for="ExamenVM.Examen.ArchivoURL" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="ExamenVM.Examen.NumeroColegiadoMedico" class="form-label">Médico Tratante</label>
                <select asp-for="ExamenVM.Examen.NumeroColegiadoMedico" asp-items="@Model.MedicoTratanteVM.MedicoTratanteList" class="form-select">
                    <option value="0">--- Seleccionar Médico ---</option>
                </select>
            </div>

            <div class="mb-3">
                <label asp-for="ExamenVM.Examen.CedulaPaciente" class="form-label">Cédula del Paciente</label>
                <input asp-for="ExamenVM.Examen.CedulaPaciente" class="form-control" readonly />
                <span asp-validation-for="ExamenVM.Examen.CedulaPaciente" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary me-3">Guardar</button>
                <a asp-area="Medicina" asp-controller="Paciente" asp-action="ExamenesMedicos" asp-route-id="@Model.ExamenVM.Examen.CedulaPaciente" class="btn btn-secondary">Regresar a la lista</a>
            </div>

        </form>
    </div>
</div>

Areas/Medicina/Views/Paciente/AgregarMedicamentos.cshtml
@using ProyectoProgramadoLenguajes2024.Models.ViewModels
@model ExpedienteVM

<div class="container">
    <div class="row pt-4">
    <div class="col-6">
        <h2 class="text-primary">
            Agregar Medicamento
        </h2>
    </div>
<form asp-action="AgregarMedicamentos" method="post">

    <div class="form-floating mb-3">
        <select asp-for="MedicamentosPacientesVM.MedicamentosPacientes.IdMedicamento" asp-items="@Model.MedicamentoVM.MedicamentoList" class="form-select">
            <option value="0">--- Selecccionar Medicamento ---</option>
        </select>
    </div>

    <div class="form-group mb-3">
        <label asp-for="MedicamentosPacientesVM.MedicamentosPacientes.CedulaPaciente" class="control-label">Cédula del Paciente</label>
        <input asp-for="MedicamentosPacientesVM.MedicamentosPacientes.CedulaPaciente" class="form-control" readonly/>
        <span asp-validation-for="MedicamentosPacientesVM.MedicamentosPacientes.CedulaPaciente" class="text-danger"></span>
    </div>



    <div class="form-floating mb-3">
        <select asp-for="MedicamentosPacientesVM.MedicamentosPacientes.NumeroColegiadoMedico" asp-items="@Model.MedicoTratanteVM.MedicoTratanteList" class="form-select">
            <option value="0">--- Selecccionar Medico ---</option>
        </select>
    </div>

    <div class="form-group d-flex justify-content-between">
        <a asp-area="Medicina" asp-controller="Paciente" asp-action="Medicamentos" asp-route-id="@Model.MedicamentosPacientesVM.MedicamentosPacientes.CedulaPaciente" class="btn btn-secondary">Volver</a>
        <input type="submit" value="Agregar" class="btn btn-primary" />
    </div>
</form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Medicina/Views/Paciente/AgregarNotasMedicas.cshtml
@using ProyectoProgramadoLenguajes2024.Models.ViewModels
@model ExpedienteVM

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Agregar Nota Medica
            </h2>
        </div>
        <form asp-action="AgregarNotasMedicas" method="post">

            <div class="mb-3">
                <label asp-for="NotaMedicaVM.NotaMedica.Texto" class="p-0"></label>
                <textarea asp-for="NotaMedicaVM.NotaMedica.Texto" rows="3" type="text" class="form-control"> </textarea>
                <span asp-validation-for="NotaMedicaVM.NotaMedica.Texto" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <select asp-for="NotaMedicaVM.NotaMedica.NumeroColegiadoMedico" asp-items="@Model.MedicoTratanteVM.MedicoTratanteList" class="form-select">
                    <option value="0">--- Selecccionar Medico ---</option>
                </select>
            </div>

            <div class="form-group mb-3">
                <label asp-for="NotaMedicaVM.NotaMedica.CedulaPaciente" class="control-label">Cédula del Paciente</label>
                <input asp-for="NotaMedicaVM.NotaMedica.CedulaPaciente" class="form-control" readonly />
                <span asp-validation-for="NotaMedicaVM.NotaMedica.CedulaPaciente" class="text-danger"></span>
            </div>

            <div class="form-group d-flex justify-content-between">
                <a asp-area="Medicina" asp-controller="Paciente" asp-action="Medicamentos" asp-route-id="@Model.NotaMedicaVM.NotaMedica.CedulaPaciente" class="btn btn-secondary">Volver</a>
                <input type="submit" value="Agregar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@section Scripts {

    <script src="https://cdn.tiny.cloud/1/ctahx4irh6zdoqsfbhcis41kqbvlddxv5q95z7jilisn62pa/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
          selector: 'textarea',
          plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage advtemplate ai mentions tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss markdown',
          toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
          tinycomments_mode: 'embedded',
          tinycomments_author: 'Author name',
          mergetags_list: [
            { value: 'First.Name', title: 'First Name' },
            { value: 'Email', title: 'Email' },
          ],
          ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
        });
    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Medicina/Views/Paciente/AgregarPadecimientos.cshtml
@using ProyectoProgramadoLenguajes2024.Models.ViewModels
@model ExpedienteVM

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Agregar Padecimiento
            </h2>
        </div>
<form asp-action="AgregarPadecimientos" method="post">
  
    <div class="form-floating mb-3">
        <select asp-for="PadecimientosPacientesVM.PadecimientoPaciente.IdPadecimiento" asp-items="@Model.PadecimientoVM.PadecimientoList" class="form-select">
            <option value="0">--- Selecccionar Padecimiento ---</option>
        </select>
    </div>

    <div class="form-group mb-3">
        <label asp-for="PadecimientosPacientesVM.PadecimientoPaciente.CedulaPaciente" class="control-label">Cédula del Paciente</label>
        <input asp-for="PadecimientosPacientesVM.PadecimientoPaciente.CedulaPaciente" class="form-control" readonly/>
        <span asp-validation-for="PadecimientosPacientesVM.PadecimientoPaciente.CedulaPaciente" class="text-danger"></span>
    </div>

   

    <div class="form-floating mb-3">
        <select asp-for="PadecimientosPacientesVM.PadecimientoPaciente.NumeroColegiadoMedico" asp-items="@Model.MedicoTratanteVM.MedicoTratanteList" class="form-select">
            <option value="0">--- Selecccionar Medico ---</option>
        </select>
    </div>

    <div class="form-group d-flex justify-content-between">
        <a asp-area="Medicina" asp-controller="Paciente" asp-action="Padecimientos" asp-route-id="@Model.PadecimientosPacientesVM.PadecimientoPaciente.CedulaPaciente" class="btn btn-secondary">Volver</a>
        <input type="submit" value="Agregar" class="btn btn-primary" />
    </div>
</form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Medicina/Views/Paciente/AgregarTratamientos.cshtml
@using ProyectoProgramadoLenguajes2024.Models.ViewModels
@model ExpedienteVM

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Agregar Tratamiento
            </h2>
        </div>
<form asp-action="AgregarTratamientos" method="post">

    <div class="form-floating mb-3">
        <select asp-for="TratamientosPacientesVM.TratamientosPacientes.IdTratamiento" asp-items="@Model.TratamientoVM.TratamientoList" class="form-select">
            <option value="0">--- Selecccionar Tratamiento ---</option>
        </select>
    </div>

    <div class="form-group mb-3">
        <label asp-for="TratamientosPacientesVM.TratamientosPacientes.CedulaPaciente" class="control-label">Cédula del Paciente</label>
        <input asp-for="TratamientosPacientesVM.TratamientosPacientes.CedulaPaciente" class="form-control" readonly/>
        <span asp-validation-for="TratamientosPacientesVM.TratamientosPacientes.CedulaPaciente" class="text-danger"></span>
    </div>



    <div class="form-floating mb-3">
        <select asp-for="TratamientosPacientesVM.TratamientosPacientes.NumeroColegiadoMedico" asp-items="@Model.MedicoTratanteVM.MedicoTratanteList" class="form-select">
            <option value="0">--- Selecccionar Medico ---</option>
        </select>
    </div>

    <div class="form-group d-flex justify-content-between">
        <a asp-area="Medicina" asp-controller="Paciente" asp-action="Tratamientos" asp-route-id="@Model.TratamientosPacientesVM.TratamientosPacientes.CedulaPaciente" class="btn btn-secondary">Volver</a>
        <input type="submit" value="Agregar" class="btn btn-primary" />
    </div>
</form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Medicina/Views/Paciente/Index.cshtml
@{
    ViewData["Title"] = "Lista de Pacientes";
}

<partial name="_Notifications" />

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Lista de Pacientes
            </h2>
        </div>
    </div>

    <table id="tblData" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Cédula</th>
                <th>Nombre Completo</th>
                <th>Correo Electronico</th>
                <th>Acciones</th>
            </tr>
        </thead>
    </table>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/paciente.js"></script>