Models/MedicoTratante.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProyectoProgramadoLenguajes2024.Models
{
    public class MedicoTratante
    {
        [Required]
        public int Cedula { get; set; }

        [Key]
        public int NumeroColegiado { get; set; }

        [Required]
        public string NombreCompleto { get; set; }

        [Required]
        public string FotoURL { get; set; }

    }
}

Areas/Admin/Controllers/MedicoTratanteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoProgramadoLenguajes2024.Data.Repository.Interfaces;
using ProyectoProgramadoLenguajes2024.Models.ViewModels;
using ProyectoProgramadoLenguajes2024.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using ProyectoProgramadoLenguajes2024.Utilities;
using System.Collections;
using System.Linq;
using ProyectoProgramadoLenguajes2024.Data.Migrations;

namespace ProyectoProgramadoLenguajes2024.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]

    public class MedicoTratanteController : Controller
    {

        #region Properties_Constructor
        private IUnitOfWork _unitOfWork;
        private IWebHostEnvironment _webHostEnvironment;

        public MedicoTratanteController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }
        #endregion


        #region HTTP_GET

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            Especialidad_MedicoTratanteVM myMedico = new Especialidad_MedicoTratanteVM
            {
                MedicoTratanteVM = new MedicoTratanteVM
                {
                    MedicoTratante = new Models.MedicoTratante(),
                    MedicoTratanteList = _unitOfWork.MedicoTratantes.GetAll().Select(i => new SelectListItem
                    {
                        Text = i.NombreCompleto,
                        Value = i.NumeroColegiado.ToString()
                    }).ToList()
                },
                EspecialidadVM = new EspecialidadVM
                {
                    EspecialidadList = _unitOfWork.Especialidades.GetAll().Select(e => new SelectListItem
                    {
                        Text = e.Nombre,
                        Value = e.Id.ToString()
                    }).ToList()
                }
            };

            if (id != null && id != 0)
            {
                myMedico.MedicoTratanteVM.MedicoTratante = _unitOfWork.MedicoTratantes.Get(x => x.NumeroColegiado == id);
                if (myMedico.MedicoTratanteVM.MedicoTratante == null)
                {
                    return NotFound();
                }
            }

            return View(myMedico);
        }

        #endregion


        #region HTTP_POST

        [HttpPost]
        public IActionResult Upsert(Especialidad_MedicoTratanteVM especialidad_MedicoTratanteVM, IFormFile? file)
        {
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString();
                string extension = Path.GetExtension(file.FileName);
                var uploads = Path.Combine(wwwRootPath, @"images\medicos");

                if (especialidad_MedicoTratanteVM.MedicoTratanteVM.MedicoTratante.FotoURL != null)
                {
                    var oldImageUrl = Path.Combine(wwwRootPath, especialidad_MedicoTratanteVM.MedicoTratanteVM.MedicoTratante.FotoURL);
                    if (System.IO.File.Exists(oldImageUrl))
                    {
                        System.IO.File.Delete(oldImageUrl);
                    }
                }

                using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }

                especialidad_MedicoTratanteVM.MedicoTratanteVM.MedicoTratante.FotoURL = @"images\medicos\" + fileName + extension;
            }
            else
            {
                if (especialidad_MedicoTratanteVM.MedicoTratanteVM.MedicoTratante.NumeroColegiado != 0)
                {
                    var existingMedico = _unitOfWork.MedicoTratantes.Get(x => x.NumeroColegiado == especialidad_MedicoTratanteVM.MedicoTratanteVM.MedicoTratante.NumeroColegiado);
                    if (existingMedico != null)
                    {
                        especialidad_MedicoTratanteVM.MedicoTratanteVM.MedicoTratante.FotoURL = existingMedico.FotoURL;
                    }

                }
            }

            var medicoTratante = _unitOfWork.MedicoTratantes.Get(x => x.NumeroColegiado == especialidad_MedicoTratanteVM.MedicoTratanteVM.MedicoTratante.NumeroColegiado);

            if (medicoTratante == null)
            {
                _unitOfWork.MedicoTratantes.Add(especialidad_MedicoTratanteVM.MedicoTratanteVM.MedicoTratante);
            }
            else
            {
                _unitOfWork.MedicoTratantes.Detach(medicoTratante);
                _unitOfWork.MedicoTratantes.Update(especialidad_MedicoTratanteVM.MedicoTratanteVM.MedicoTratante);
            }

            _unitOfWork.Save();

            if (especialidad_MedicoTratanteVM.MedicoTratanteVM.Especialidad != 0)
            {
                addEspecialidad_MedicoTratante(especialidad_MedicoTratanteVM.MedicoTratanteVM.MedicoTratante.NumeroColegiado, especialidad_MedicoTratanteVM.MedicoTratanteVM.Especialidad);
            }
            TempData["success"] = "Médico Tratante agregado exitosamente";

            return RedirectToAction("Index");


        }

        public void addEspecialidad_MedicoTratante(int numeroColegiado, int especialidad)
        {
            Especialidad_MedicoTratante especialidadToAdd = new()
            {
                MedicoTratanteId = numeroColegiado,
                EspecialidadId = especialidad
            };

            _unitOfWork.Especialidades_MedicoTratantes.Add(especialidadToAdd);
            _unitOfWork.Save();
        }

        #endregion


        #region API
        public IActionResult GetAll()
        {
            var medicoTratanteList = _unitOfWork.MedicoTratantes.GetAll().Select(c => new
            {
                c.Cedula,
                c.NumeroColegiado,
                c.NombreCompleto
            });
            return Json(new { data = medicoTratanteList });

        }

        [HttpGet]
        public IActionResult Detalles(int? id)
        {
            Especialidad_MedicoTratanteVM myMedico = new Especialidad_MedicoTratanteVM
            {
                MedicoTratanteVM = new MedicoTratanteVM
                {
                    MedicoTratante = _unitOfWork.MedicoTratantes.Get(x => x.NumeroColegiado == id),
                    MedicoTratanteList = _unitOfWork.MedicoTratantes.GetAll().Select(i => new SelectListItem
                    {
                        Text = i.NombreCompleto,
                        Value = i.NumeroColegiado.ToString()
                    }).ToList()
                },
                EspecialidadVM = new EspecialidadVM
                {
                }
            };

            List<Especialidad_MedicoTratante> especialidadesMedico = _unitOfWork.Especialidades_MedicoTratantes.GetAll().Where(x => x.MedicoTratanteId == id).ToList();

            myMedico.EspecialidadVM = new EspecialidadVM
            {
                Especialidad = _unitOfWork.Especialidades.Get(x => x.Id == myMedico.MedicoTratanteVM.Especialidad),
                EspecialidadList = _unitOfWork.Especialidades.GetAll().Select(e => new SelectListItem
                {
                    Text = e.Nombre,
                    Value = e.Id.ToString()
                }).ToList()
            };

            myMedico.EspecialidadVM.EspecialidadList = myMedico.EspecialidadVM.EspecialidadList.Where(x => especialidadesMedico.Any(y => y.EspecialidadId == int.Parse(x.Value))).ToList();

            if (id != null && id != 0)
            {
                myMedico.MedicoTratanteVM.MedicoTratante = _unitOfWork.MedicoTratantes.Get(x => x.NumeroColegiado == id);
                if (myMedico.MedicoTratanteVM.MedicoTratante == null)
                {
                    return NotFound();
                }
            }

            return View(myMedico);
        }
        #endregion

        #region Borrar
        public IActionResult Delete(int? id)
        {
            try
            {
                var medicoTratante = _unitOfWork.MedicoTratantes.Get(x => x.NumeroColegiado == id);
                
                if (medicoTratante != null)
                {
                    var padecimientosPaciente = _unitOfWork.PadecimientosPacientes.GetAll().Where(x => x.CedulaPaciente == id).ToList();
                    var tratamientosPaciente = _unitOfWork.TratamientosPacientes.GetAll().Where(x => x.CedulaPaciente == id).ToList();
                    var medicamentosPaciente = _unitOfWork.MedicamentosPacientes.GetAll().Where(x => x.CedulaPaciente == id).ToList();
                    var examenesPaciente = _unitOfWork.ExamenesPacientes.GetAll().Where(x => x.CedulaPaciente == id).ToList();
                    var notasMedicas = _unitOfWork.NotasMedicas.GetAll().Where(x => x.CedulaPaciente == id).ToList();

                    foreach (var padecimientoPaciente in padecimientosPaciente)
                    {
                        _unitOfWork.PadecimientosPacientes.Remove(padecimientoPaciente);
                    }

                    foreach (var tratamientoPaciente in tratamientosPaciente)
                    {
                        _unitOfWork.TratamientosPacientes.Remove(tratamientoPaciente);
                    }

                    foreach (var medicamentoPaciente in medicamentosPaciente)
                    {
                        _unitOfWork.MedicamentosPacientes.Remove(medicamentoPaciente);
                    }

                    foreach (var examenPaciente in examenesPaciente)
                    {
                        _unitOfWork.ExamenesPacientes.Remove(examenPaciente);
                    }

                    foreach (var notaMedica in notasMedicas)
                    {

Areas/Admin/Views/MedicoTratante/Detalles.cshtml
@using System.Globalization;
@using ProyectoProgramadoLenguajes2024.Models.ViewModels
@model Especialidad_MedicoTratanteVM

<div class="card  container pt-4">
    <div class="card-header bg-primary text-light ml-0  row ">
        <div class="col-12 col-md-6">
            <h1 class="text-dark-50">@Model.MedicoTratanteVM.MedicoTratante.NombreCompleto</h1>

        </div>
    </div>
    <div class="card-body row container">
        <div class="container rounded p-2">
            <div class="row">
                <div class="col-8 col-lg-8">
                    <div class="row pl-2">
                        <p class="text-black" style="font-size: 1.5rem;">
                            <strong>Numero de Colegiado:</strong> @Model.MedicoTratanteVM.MedicoTratante.NumeroColegiado
                            <br />
                            <strong>Especialidades:</strong>
                            @foreach (var item in Model.EspecialidadVM.EspecialidadList)
                            {
                                <span>@item.Text</span>

                                <br />
                            }
                        </p>
                    </div>
                </div>
                <div class="col-12 col-lg-3 offset-lg-1 text-center">
                    <img src="~/@Model.MedicoTratanteVM.MedicoTratante.FotoURL" width="100%" class="rounded" />
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <div class="row">
            <div class="col-12 col-md-6 pb-1">
                <a class="btn btn-primary  d-flex align-items-center justify-content-center" style="height: 50px; width: 150px;" asp-area="Admin" asp-controller="MedicoTratante" asp-action="Index">
                    Volver a la lista
                </a>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/MedicoTratante/Index.cshtml
@{
    ViewData["Title"] = "Lista de Médicos Tratantes";
}


<partial name="_Notifications" />

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Lista de Médicos Tratantes
            </h2>
        </div>
       
    </div>

    <table id="tblData" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Cedula</th>
                <th>Numero de Colegiado</th>
                <th>Nombre Completo</th>
                <th>Acciones</th>
            </tr>
        </thead>
    </table>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/MedicoTratante.js"></script>

Areas/Admin/Views/MedicoTratante/Upsert.cshtml
@using ProyectoProgramadoLenguajes2024.Models.ViewModels
@model Especialidad_MedicoTratanteVM
<partial name="_Notifications" />

<form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <h2 class="text-primary"> @(Model.MedicoTratanteVM.MedicoTratante.NumeroColegiado == 0 ? "Agregar" : "Modificar") Médico Tratante</h2>
        </div>   
        <div class="mb-3">
            <div class="mb-3">
                <label asp-for="MedicoTratanteVM.MedicoTratante.NumeroColegiado" class="p-0">Número de Colegiado</label>
                @if (Model.MedicoTratanteVM.MedicoTratante.NumeroColegiado != 0)
                {
                    <input asp-for="MedicoTratanteVM.MedicoTratante.NumeroColegiado" type="number" class="form-control" readonly />
                <label asp-for="MedicoTratanteVM.MedicoTratante.Cedula" class="p-0">Cedula</label>
                <input asp-for="MedicoTratanteVM.MedicoTratante.Cedula" type="number" class="form-control" readonly />
                }
                else
                {
                    <input asp-for="MedicoTratanteVM.MedicoTratante.NumeroColegiado" type="number" class="form-control" />
                }
                <span asp-validation-for="MedicoTratanteVM.MedicoTratante.NumeroColegiado" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="MedicoTratanteVM.MedicoTratante.NombreCompleto" class="p-0">Nombre Completo</label>
                <input asp-for="MedicoTratanteVM.MedicoTratante.NombreCompleto" type="text" class="form-control" />
                <span asp-validation-for="MedicoTratanteVM.MedicoTratante.NombreCompleto" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="MedicoTratanteVM.MedicoTratante.FotoURL" class="p-0">Foto</label>
                <input id="uploadBox" name="file" type="file" class="form-control" />
                <span asp-validation-for="MedicoTratanteVM.MedicoTratante.FotoURL" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <select asp-for="MedicoTratanteVM.Especialidad" asp-items="@Model.EspecialidadVM.EspecialidadList" class="form-select">
                    <option value="0">--- Selecccionar Especialidad ---</option>
                </select>
            </div>


            <button type="submit" class="btn btn-primary" style="width:150px">Guardar</button>
            <a asp-controller="MedicoTratante" asp-action="Index" style="width:200px" class="btn btn-secondary">Regresar a la lista</a>
        </div>
   
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}